# Generated by Django 4.2.16 on 2024-09-09 15:47

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BIM", "BIM"),
                            ("BCA", "BCA"),
                            ("CSIT", "CSIT"),
                            ("BHM", "BHM"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("year", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "folder_category",
                    models.CharField(
                        choices=[
                            ("Entrance", "Entrance"),
                            ("Old Questions", "Old Questions"),
                            ("Prospectus", "Prospectus"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(upload_to=backend.models.custom_upload_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
