# Generated by Django 4.2.16 on 2024-09-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="college_or_university",
            field=models.CharField(
                blank=True,
                choices=[("College", "College"), ("University", "University")],
                max_length=100,
                null=True,
            ),
        ),
    ]
