# Generated by Django 4.2.16 on 2024-09-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_upload_college_or_university"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "First"),
                    ("2", "Second"),
                    ("3", "Third"),
                    ("4", "Fourth"),
                    ("5", "Fifth"),
                    ("6", "Sixth"),
                    ("7", "Seventh"),
                    ("8", "Eighth"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="folder_category",
            field=models.CharField(
                choices=[
                    ("Entrance", "Entrance"),
                    ("Old Questions", "Old Questions"),
                    ("Prospectus", "Prospectus"),
                    ("Syllabus", "Syllabus"),
                ],
                max_length=100,
            ),
        ),
    ]
